### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by Anusien** [eDonnes124/Town-Of-Us-R#1]
I know this is a kind of awkward way to do this, but I couldn't find any other contact information for you. I see you've picked up where Town of Us left off. I have too; you can see my [version](https://github.com/Anusien/Town-Of-Us). For example, I see from the changelogs that you also caught some significant bugs like the one where the host doesn't have any cooldowns for roles or crashing the game on vanilla impostors. I think it might make more sense for us to join forces somehow and present a single inheritor to Town of Us.

You can find me on Discord at Anusien#5418; that's probably the easiest way to talk.

**Comment by cootshk** [comment]
isn't BToU also a thing?
