### ISSUE TITLE
New Role (Crook)

### ISSUE THREAD

**Issue by Maikiz** [eDonnes124/Town-Of-Us-R#10]
Crook (Neutral Role)
Steals the ability to convene meetings once per (configurable amount of time).
Can call meetings as many times as the buttons were stolen.
If during the voting he alone votes for a player, then this player will be prohibited from using his role during this round.
Wins if no one in the game has the opportunity to call a meeting except him.

**Comment by apacrep** [comment]
why are these roles not in mod?

**Comment by Anusien** [comment]
How does this role win?

**Comment by Maikiz** [comment]
> How does this role win?
When Crook takes all the buttons from all the players.

**Comment by Anusien** [comment]
Isn't this basically just the Arsonist?
