### ISSUE TITLE
[Suggestion] Night vision cams.

### ISSUE THREAD

**Issue by ItsPyzen** [eDonnes124/Town-Of-Us-R#100]
Hey!
I had a fun idea and wanted to hear ur opinion on it:

When the lights get sabbotaged, maybe its a cool idea that the cams go into night vision mode. And when that happends maybe have a little static/glitchy animation when this happends so it will make it a little more difficult to see for a few seconds what is happening near a cam

**Comment by eDonnes124** [comment]
I do like this idea, but sadly don't really have much idea on how to make this possible.
