### ISSUE TITLE
10-21-2022 Recent downloads fail to launch

### ISSUE THREAD

**Issue by Voltainus** [eDonnes124/Town-Of-Us-R#101]
Tried running a game of town of us and for the people that didn't have it we attempted to walk them through the download and once we went to launch and it failed to launch the mod. it only booted the base game.

**Comment by eDonnes124** [comment]
Most recent Among Us update is not compatible with Town Of Us. We are waiting for BepInEx 661 to update the mod.

**Comment by sandtechnology** [comment]
> Most recent Among Us update is not compatible with Town Of Us. We are waiting for BepInEx 661 to update the mod.

https://builds.bepinex.dev/projects/bepinex_be
661 and 662 has released there, and I have done the reactor and Town-Of-Us migrate works before it, would it needs any changes for creating PR?
