### ISSUE TITLE
Upgraded PC and TOU won't launch

### ISSUE THREAD

**Issue by Donartius** [eDonnes124/Town-Of-Us-R#104]
Upgraded my PC and TOU won't launch.
I get to the "Among Us Loading" screen, the game force quits. 
Tried using this work-around for stuttering https://github.com/eDonnes124/Town-Of-Us-R/issues/81, but it doesn't work.

PC Specs:
CPU: AMD Ryzen 5 7600X (6 Cores)
GPU: AMD Radeon RX 6800
RAM: 32GB
MOBO: MSI PRO B650-P WiFi AM5

**Comment by whichtwix** [comment]
mod doesnt work on latest among us version right now, have to go properties,betas, select public beta

**Comment by firebird5555** [comment]
> mod doesnt work on latest among us version right now, have to go properties,betas, select public beta in steam

i just tried this and it still crashes after the intro screen. Not sure if im doing something wrong? im just copying the files into the among us folder

**Comment by Awsomonium** [comment]
> mod doesnt work on latest among us version right now, have to go properties,betas, select public beta in steam

Specifically Public-Previous to roll back to last update.

**Comment by whichtwix** [comment]
> Specifically Public-Previous to roll back to last update.

thats normally the case but this time innersloth didnt update the branch, public previous gives 9.20 and you need 10.25

**Comment by Donartius** [comment]
> > Specifically Public-Previous to roll back to last update.
> 
> thats normally the case but this time innersloth didnt update the branch, public previous gives 9.20 and you need 10.25 so you will need the "public beta" not the the "public previous"

Thank you! thats seemed to have fixed it
