### ISSUE TITLE
Patch Note on Github

### ISSUE THREAD

**Issue by vipers-web-design** [eDonnes124/Town-Of-Us-R#112]
When you upload a new Release version here on Github, why don't you include the patch notes too?

What if people don't have discord? Or have joined the maximum number of servers already?

I personally would love to stop copying your entire Discord post and pasting it on a server I am only a **_basic member_** of.

**Comment by whichtwix** [comment]
patches notes are in the readme under the chanelog section

**Comment by vipers-web-design** [comment]
They may be there but look at your competitor "The Other Roles". They put their patch notes in the README file, but they also make them easier to find when they upload a new release [https://github.com/TheOtherRolesAU/TheOtherRoles/releases/tag/v4.2.1](https://github.com/TheOtherRolesAU/TheOtherRoles/releases/tag/v4.2.1)

**Comment by eDonnes124** [comment]
I can start including this it isn't much of a problem.
