### ISSUE TITLE
How to change source code?

### ISSUE THREAD

**Issue by Bartix2765236** [eDonnes124/Town-Of-Us-R#117]
Where is source code in files?

**Comment by Bartix2765236** [comment]
Could you explain me step by step?

**Comment by Bartix2765236** [comment]
With screenshots?

**Comment by Bartix2765236** [comment]
![image](https://user-images.githubusercontent.com/106704888/224725910-1898df05-3cac-4f54-beee-3d7121bbd836.png)
First, where is code in files?

**Comment by whichtwix** [comment]
its not in the files

**Comment by Bartix2765236** [comment]
okay, next?

**Comment by whichtwix** [comment]
now just extract the zip and you can start editting the code, when you want to make the dll to be able to play with it, open command prompt, write ```cd``` and then copy paste the path where you extracted, click enter. then run ```dotnet build```

**Comment by Bartix2765236** [comment]
ok thanks and that's it?

**Comment by Bartix2765236** [comment]
and how to run it?

**Comment by Bartix2765236** [comment]
> 

cd...
can you give an example?

**Comment by whichtwix** [comment]
```cd C:\Program Files\Epic Games\AmongUs```, it means my cmd window is taken to that folder

**Comment by Bartix2765236** [comment]
Thanks! And where is src/bin/debug/net6.0/townofus.dll?
Can you give screenshots?

**Comment by Bartix2765236** [comment]
Or examples?

**Comment by whichtwix** [comment]
> and what make the dll? ![image](https://user-images.githubusercontent.com/106704888/225701170-f48edfe7-3e2d-4183-807f-b0bf24f41466.png)

after you run dotnet build, click the src folder here, then click bin, then debug..etc..youll finally see a townofus.dll
