### ISSUE TITLE
[Suggestion] Merge a few roles

### ISSUE THREAD

**Issue by AlchlcDvl** [eDonnes124/Town-Of-Us-R#124]
Going off your point of the mod being cluttered in [#111](https://github.com/eDonnes124/Town-Of-Us-R/issues/111#issuecomment-1414740521), it would good to merge the following roles
- Spy with Investigator so at least Spy becomes useful again + bring back its vitals TOD abilities
- Vigilante with Assassin (basically make Assassin available to Crew as well)
- Mystic and Seer since both a kind of weak so either a buff for each or a merge is good

These should open up slots for more roles for the future

**Comment by eDonnes124** [comment]
I disagree, Seer is the only role which I would even consider replacing/merging, as Detective was designed to be a Seer rework as a lot of people didn't like Seer so I wanted to give an alternative option to it, although Detective was very weak on launch. And being real I'm pretty happy with all the roles in the mod at the moment besides Altruist and every role feels like it provides enough to be justified to be it's own role and balanced in their own way (although some roles can be tweaked a little).

**Comment by AlchlcDvl** [comment]
Ah then at the very least maybe an active ability that can be used by the Spy because as of right now, its only ability is to be able to see colors on the Admin Table makes it pretty vulnerable to comms sabotages and assassin guesses.

But one thing I really want to be seen is Spy being fully reinstated, as it originally used to be able to tell a player's time of death on vitals but the feature was long forgotten when the 15+ player update came out

**Comment by AlchlcDvl** [comment]
Unless of course, I'm bricked, never bothered to check if Spy vitals work again and that they do work

**Comment by MrWeasel1000** [comment]
> Unless of course, I'm bricked, never bothered to check if Spy vitals work again and that they do work

Spy could maybe have the ability to either go invisible at anytime (with a cooldown) or check cams from anywhere. 

The invisibility ability is purely so it can be used to make checking admin (checking who is with who) feel more, like you have to check admin then go invisible. 

The cams part is just there as an extra ability.

**Comment by alecxvs** [comment]
> Vigilante with Assassin (basically make Assassin available to Crew as well)

I wouldn't make vigilante a modifier, I would do the opposite and split them. Make assassin an imposter role like in cultist mode. Or maybe do both (and give a toggle between assassin as a modifier or a role)

You could probably even make a neutral assassin role like "Mercenary" or something who has to assassinate a certain player before the end of the game to win

**Comment by MrWeasel1000** [comment]
> > Vigilante with Assassin (basically make Assassin available to Crew as well)
> 
> 
> 
> I wouldn't make vigilante a modifier, I would do the opposite and split them. Make assassin an imposter role like in cultist mode. Or maybe do both (and give a toggle between assassin as a modifier or a role)
> 
> 
> 
> You could probably even make a neutral assassin role like "Mercenary" or something who has to assassinate a certain player before the end of the game to win

That is basically executioner but assassin-fied don't know if it's really worth reworking the role to not really change up the ending, but what does Donners think?

**Comment by AlchlcDvl** [comment]
> > Vigilante with Assassin (basically make Assassin available to Crew as well)
> 
> I wouldn't make vigilante a modifier, I would do the opposite and split them. Make assassin an imposter role like in cultist mode. Or maybe do both (and give a toggle between assassin as a modifier or a role)
> 
> You could probably even make a neutral assassin role like "Mercenary" or something who has to assassinate a certain player before the end of the game to win

sounds like a cool thing, but we don't want too many targetting type roles in the game otherwise they are no fun
