### ISSUE TITLE
v4.0.3 does not work with latest Among Us update. Sign in does not work. Details within.

### ISSUE THREAD

**Issue by Awsomonium** [eDonnes124/Town-Of-Us-R#126]
The initial sign in (where the screen has an overlay without a dialogue box over the main menu and you cannot click on anything) stays on screen until it says "It seems to be taking a while to sign in, do you want to continue to wait or try offline mode."

'Continue to wait' option just repeats the same until the prompt comes up again.

For clarification, the mod is still visible to the game. (as in in top right corner still has the 'mod' icon and the build info is still on the top left like normal. It's just that the sign in overlay prevents you from clicking on anything while it is still attempting to sign in.

For those that see this with this issue, current solve (at least on Steam version, don't know if you can roll back on other platforms) is to roll back to the previous release. To do this go to Properties > Betas > Select Public-Previous from the drop down.

**Comment by whichtwix** [comment]
even if its there the majority of people wont see it or forget it, then proceed to ask

**Comment by Awsomonium** [comment]
> yeah, most times a new among us version comes out tou becomes incompatible with it, the next update will be made for the current version
> 
> also, the the mod icon and build info comes from tou's dependency mod, reactor, to know if tou has loaded check if theres a tou banner in the main menu at the center

I figured, but raised the issue anyway, in case it helped in any way with the next version. Plus, I know sometimes the mod icon wouldn't show at all in a new update.



> maybe there should be a disclaimer on the readme that when among us updates, the mod _**will not**_ work on the latest version
> 
> it gets a little annoying to see people say "mod version X does not work on among us version Y" like maybe try taking some time to read the releases section to see that the latest version of the mod =/= works on the latest version of among us
> 
> im not trying to be rude here it's just my brutally honest opinion

That's fair enough. 
It was more to provide info that could potentially help with building the new version more than anything else. I've been using the mod long enough to know how the update cycle works. Maybe I should've made the title something different, but it was the most to-the-point thing I had. I just know that my friends who do programming like as much specific feedback as possible when updating stuff and I saw no one had yet, so down the info I had.
