### ISSUE TITLE
assassin and retributionist 

### ISSUE THREAD

**Issue by apacrep** [eDonnes124/Town-Of-Us-R#13]
When you kill during meetings it doesn't register kill at times although it looks to assassin or retributionist is does. also when you guess wrong you can keep guessing even though your dead and it looks to everyone like your alive

**Comment by eDonnes124** [comment]
I know, will probably release another patch tomorrow, turn off Mayor for now.

**Comment by apacrep** [comment]
So if mayor is off assassin and retri kills in meeting will register? Also are you adding additional roles listed in issues or is that just someones idea of new roles?

**Comment by TheOnlyTME** [comment]
> 
> 
> So if mayor is off assassin and retri kills in meeting will register? Also are you adding additional roles listed in issues or is that just someones idea of new roles?

they are just ideas
