### ISSUE TITLE
[Issue + Suggestion] Full Body Hats

### ISSUE THREAD

**Issue by AlchlcDvl** [eDonnes124/Town-Of-Us-R#132]
I have an issue with hats covering the entire character up, because it makes it hard to recognise player colors without colorblind mode.

My suggestion is either deleting them, or making them player color adaptive.

**Comment by eDonnes124** [comment]
I'm aware this is a complaint and I honestly can't do much about it. Most of the full body hats are by Ophidian, she is a fantastic artist and has implemented over a hundred hats now I think into Town of Us. It would firstly be a disservice to her to remove them and the amount of effort to make them all colour adaptive would be so much work but also wouldn't make sense for a lot of them so can't really do much about it. Using the colourblind base Among Us setting is the only real way around it.

**Comment by AlchlcDvl** [comment]
i see
