### ISSUE TITLE
No kill/death animation

### ISSUE THREAD

**Issue by veppman** [eDonnes124/Town-Of-Us-R#134]
I recently downloaded the zip for 4.0.5s when I launch the game it launches fine I am able to get into a lobby but when I die I do not see any animation for it, when I attempt to use the kill button on killing roles it is not working, when a meeting is called I see the initial color of the body being discovered but the following screen that shows the number of potential bodies shows no bodies found but it will show who initially dies in the meeting

When someone with guessing powers either guesses or guesses incorrectly it does not show the animation of them dying/killing and it will still show them alive and I am unable to use the guessing ability when I have it

So far I have uninstalled reinstalled the base game, put the extracted zip file into the root of my C drive cleared my temp files on my computer and rebooted multiple times but it still is not working

I have even tried to run the game as an admin but no luck

If anyone has any suggestions please let me know

**Comment by whichtwix** [comment]
are you sure your on the latest au version, and you cant play in public lobbies on na, eu, asia

**Comment by veppman** [comment]
so far I have only been attempting it in private lobbies and the others in the lobby are not having an issue we are using the Modded NA servers

**Comment by whichtwix** [comment]
and the au version? could try reinstalling too

**Comment by veppman** [comment]
yes I have already tried uninstalling and reinstalling Among Us

**Comment by veppman** [comment]
The version it shows is 2023.3.28s

**Comment by eDonnes124** [comment]
This was hopefully fixed in the v4.0.6s update as I can't replicate it.

**Comment by veppman** [comment]
Hello,

So I learned it was my laptop at the time

It is a company owned device and it was flagging 2 of the dll files at the
time as Malware

i have it enough time and eventually it stopped flagging them

Thank you for your assistance though
