### ISSUE TITLE
Amnesiac remembering Amnesiac turns both into Survivors

### ISSUE THREAD

**Issue by tezer2d** [eDonnes124/Town-Of-Us-R#136]
When an Amnesiac remembers the role of another Amnesiac, they both become Survivors. This is unexpected, because the Amnesiac picked up the role Amnesiac and should therefore still be Amnesiac, not Survivor.
![1_censored](https://user-images.githubusercontent.com/132029925/235037791-d9f571b4-4a55-4fac-ae67-bd903606795f.png)
(Names in screenshots are removed for privacy reasons) Here player A (Amnesiac) remembered player B's role (Amnesiac) but both became Survivor.
Theory what causes this: When a dead imposter has their role remembered, they just become a regular vanilla impostor. Similarly, a crew role just becomes a regular vanilla crewmate. But in the case of neutral roles, the setting is that they become Survivor.
![2_censored](https://user-images.githubusercontent.com/132029925/235038050-3b8820c2-b956-4a70-8af8-80144fbda862.png)
So when the alive Amnesiac remembers the dead Amnesiac, the dead one becomes Survivor, and the alive one becomes Amnesiac a second time. 
But because the "remember" ability has no cooldown, it's just used again, and this time the alive Amnesiac takes the role of the dead Survivor, therefore the alive Amnesiac becomes alive Survivor and the dead Survivor becomes dead Survivor a second time
this causes the roles in the screenshot to be
Amne -> Amne -> Surv (for the alive person, here player A)
and
Amne -> Surv -> Surv (for the dead person, here player B)

How to fix: 
Make it so that dead neutrals that have their role remembered become Amnesiacs. That way when an Amnesiac remembers an Amnesiac both will just remain Amnesiacs. Furthermore, after an Amnesiac has remembered any neutral role, turning the corpse into an Amnesiac corpse, no other Amnesiacs can get any role out of the corpse. 
Also a cooldown would have to be added to the "remember" ability (like 1 sec) to prevent a continuous remembering which could cause lag.

**Comment by eDonnes124** [comment]
This is intentional.
