### ISSUE TITLE
[Bug] Kill button is not present as impostor, keybinds are not working

### ISSUE THREAD

**Issue by haaldor** [eDonnes124/Town-Of-Us-R#137]
So if I install Among Us from Steam it works perfectly fine, but if I install TOUR on top of it, few issues occur:
1. Keybinds are not working. Neither escape for the menu, Q for kill, E to interact, venting, any custom keybinds... nothing.
2. If I'm a killing role, kill button doesn't exist. Other buttons are there, but the kill button just doesn't show up.

I tried so far:
1. Reinstalling the game
2. Installing the combination of Among us v2023.2.28 and TOUR v.4.0.3
3. Installing the combination of Among us v2023.3.28 and TOUR v.4.0.4
4. Installing the combination of Among us v2023.3.28 and TOUR v.4.0.5
5. Deleting files manually
6. Deleting files through Steam
7. Deleting files from AppData/LocalLow/Innersloth
8. Moving Among us to different folder or different drive
9. Opening as Admin

So far no luck in finding any fix for that.

It's hard for me to give replication steps, as they are literally: Download Among Us from Steam and TOUR from this github, insert TOUR into Among Us folder and start it.

**Comment by whichtwix** [comment]
your not trying public lobbies right? ig what you can do is do the combination from step 4, let the bug happen, try keybinds too, then close your game, go to the among us folder/bepinex and drop the logoutput file here, it may reveal more details

**Comment by haaldor** [comment]
No, I'm using either local connection with Radmin VPN for playing or private lobbies, and for testing I'm using practice mode.

Here's the file after opening the game, going to practice mode on Skeld, changing role to impostor, going down to character in admin, pressing Q, clicking where kill button should be, going to vent, pressing vent button and finally pressing escape multiple times:
[LogOutput.log](https://github.com/eDonnes124/Town-Of-Us-R/files/11414457/LogOutput.log)

Weirdly enough it looks like errors are coming from SetTasks functions, but sadly I don't know inner workings of TOUR or Reactor too well yet.

**Comment by whichtwix** [comment]
oh i see, a quirk with the mod is vanilla imp becomes unusable, the mod actually recreates vanilla imp with its own system for use in the mod, go to among us data/boot.config, and delete the single instance= line, then open 4 instances and try a lobby with some roles on and see if it occurs there

**Comment by haaldor** [comment]
Allright, after testing with your recommendations:
1. Indeed, making normal lobby works like a charm, with all keybindings working with exception of ESC (it doesn't show settings menu, but it makes me slowly self-doubt if that was ever a thing... was it? Using ESC to open the settings menu? I'm pretty sure I used to do that)
2. When I create Hide and Seek lobby, "Start" button stops responding and doesn't do anything
3. If I'm not the lobby creator and Hide and Seek game starts, it uses normal impostor role - so I don't have kill button and "Q" doesn't work.

Interestingly enough, other players with this mod installed can kill, so I'm a bit confused.

So my question here is - is it possible to play Hide and Seek with this mod installed?
And also a thought - I wonder how tough it would be to add mod settings to practice mode as well, for testing purposes. Would be helpful for players to learn the roles, and for testing purposes as well!

**Comment by whichtwix** [comment]
the mod leaves hide n seek as is and tries to attempt to not make it buggy, tho ig it has then, and there arent any freeplay integration built in though you could use [this](https://github.com/MyDragonBreath/AmongUs.MultiClientInstancing), it lets you make bots in the lobby then start the game, then you can switch between them all ingame

as for 2, anything in the logs or no

**Comment by eDonnes124** [comment]
I can't find a way to replicate this.
