### ISSUE TITLE
[Prob a bug] Neutral roles win if crewmates do their tasks

### ISSUE THREAD

**Issue by Stivek16** [eDonnes124/Town-Of-Us-R#138]
Im pretty sure that neutral roles shouldnt win when tasks are finished, esspecially the neutral killing roles.

**Comment by AlchlcDvl** [comment]
the only neutrals capable of winning form tasks are survivors and guardian angels with crew targets

**Comment by Stivek16** [comment]
I won with pestilence by tasks once

**Comment by AlchlcDvl** [comment]
were you amnesiac turned plaguebearer by any chance?

**Comment by Stivek16** [comment]
No, but it dosent happen anymore idk why

**Comment by AlchlcDvl** [comment]
then it's probably a rare unintentional bug, try repeating the events of the game to see what might be causing it in case it happens again

**Comment by eDonnes124** [comment]
This isn't the only way for neutrals to win with crewmates. This bug has existed since the beginning of Town of Us (even before I took over). The same goes for GA/Surv sometimes not winning with Imps when they should.

**Comment by eDonnes124** [comment]
Fixed in v5.0.0.
