### ISSUE TITLE
2.3.4 issue

### ISSUE THREAD

**Issue by apacrep** [eDonnes124/Town-Of-Us-R#14]
Assassin kill does not work during meeting. It shows everyone your dead yet you can still vote during meetings and use abilities like swapper. I was swapper and killed by assassin everyone seen me dead but this is what it looked like on my screen.
![Screenshot (2)](https://user-images.githubusercontent.com/91863358/141844953-76f67a7b-15a9-4e72-bc85-108fe2441f54.png)
![Screenshot (3)](https://user-images.githubusercontent.com/91863358/141844957-e55bde0c-e3e9-4487-8be9-33d0dc2149fb.png)
r.

**Comment by whichtwix** [comment]
its a known bug that swapper continues to "live" on their screen, they are dead. I dont know if the swap also just shows for them or not

**Comment by apacrep** [comment]
Oh you can still swap and eject people who are alive
