### ISSUE TITLE
Not getting in

### ISSUE THREAD

**Issue by TirelessTraveler** [eDonnes124/Town-Of-Us-R#140]
I recently got the mod, made a new folder with all the game and mod files in the commons place where the other games are at, I go to try and get into the mod, and it gets stuck.

After a couple of seconds it stops trying to load the game, the game never visually appears, but if you try to go into it while its presumably loading it will have the "another instance of this game is already running".

Among Us works perfectly fine without the mod

**Comment by AlchlcDvl** [comment]
you are probably opening it too many times at once, open it only once and then let it load

the first time loading the mod is always long because it's trying to download the required dependencies for the mod to work
