### ISSUE TITLE
[Suggestion] A gamemode that utilizes Approval Voting for the voting-system.

### ISSUE THREAD

**Issue by Wulfstrex** [eDonnes124/Town-Of-Us-R#141]
**"You can vote for more than one and hit 'finish' when you're done."**

The gamemode that I suggest would allow each player to vote for more than just option every meeting. For example: Every player would be allowed to vote on two options, but only once on each one of them.

There would be an additional lobby-setting that comes along with it, which would let the host define for how many options at maximum can be voted for by each player every meeting, going from theoretically 2 up to 15.

 There would also be a “Finish“-button to let the players be done with voting earlier, without having been forced to use up all of their available approval-votes, even though said button could receive yet another optional lobby-setting to have it be disabled, if desired.

**This alternative voting-system should be simple to grasp for any players, even if they have only played vanilla Among Us up until now, while still leading the players into situations where they would have to use and face new strategies of social deduction, manipulation and voting to get their desired voting-outcomes to win the game.**

_It might be better to refer to it as “Disapproval“ instead, due to how the player with the most votes is going to be ejected._

_The Mayor-role would most likely have to be disabled for this gamemode, as I personally just can't see it work properly in combination with any alternative voting-systems like this one._

**Comment by eDonnes124** [comment]
I don't think this is a good idea.
