### ISSUE TITLE
Seperate Neutral Non-Killing into Neutral Benign and Neutral Evil

### ISSUE THREAD

**Issue by FERTAILS** [eDonnes124/Town-Of-Us-R#145]
Incase you add future neutral benigns/neutral evils, im suggesting that you seperate the two of them, allowing for easier customisation in terms of roles. Similar to the image below.
![Screenshot 2023-05-31 093437](https://github.com/eDonnes124/Town-Of-Us-R/assets/100311393/c8ebbe00-0cbe-468c-b54f-92f3fb71a04a)

**Comment by eDonnes124** [comment]
Added next major update.
