### ISSUE TITLE
Transporter Role Dosent work 

### ISSUE THREAD

**Issue by Wael1231** [eDonnes124/Town-Of-Us-R#147]
when i dowload TOU-R and play in Local Lobby using MCI the Transporter Role ability dosent work i mean when you click in transport and you click on a player it dosent transport

**Comment by AlchlcDvl** [comment]
that's an issue with mci then

**Comment by Wael1231** [comment]
there any thing to fix it in MCI ?

**Comment by AlchlcDvl** [comment]
edit the code yourself, mci's more of a universal-ish mod
