### ISSUE TITLE
Tou affects normal among us

### ISSUE THREAD

**Issue by qwertykid** [eDonnes124/Town-Of-Us-R#149]
The game said I was arsonist and didn't let me sabatoge becide doors.
![PXL_20230612_193200754 MP](https://github.com/eDonnes124/Town-Of-Us-R/assets/64162703/e27ce5de-3881-4e75-bc69-9e0e8e532787)

**Comment by AlchlcDvl** [comment]
that isn't tou

**Comment by AlchlcDvl** [comment]
there might be a chance you were playing a version town of host, which might be why you could sabotage as Arsonist

either way, the mod you're playing is not town of us as far as i can tell
