### ISSUE TITLE
Please Update the README.md

### ISSUE THREAD

**Issue by vipers-web-design** [eDonnes124/Town-Of-Us-R#151]
So the Imitator role, you state "It should be noted the Imitator can not imitate all crew roles."
Could you please list what roles it can imitate?

Because a friend brought up this scenario;
- Snitch is dead, also completed all tasks
- Imitator also completed all tasks, then next meeting imitates Snitch
- After the meeting, if the impostors are still alive, can the Imitator see them?

That is if Imitator can take Snitch.

**Comment by eDonnes124** [comment]
Imitator cannot use Snitch for this reason as Imps would just assassinate the Imitator.
Mayor/Snitch/Vigilante/Swapper cannot be used.
There are only 4 crew roles which can't be used and I didn't feel the need to specify this.
