### ISSUE TITLE
[Suggestion] About Neutral Evils

### ISSUE THREAD

**Issue by AlchlcDvl** [eDonnes124/Town-Of-Us-R#153]
So I'm a big fan for customising a lot of things, especially those pertaining to roles. Neutral Evil (NE from now on) roles, as they are right now, end the game upon achieving their objective. That's fun and all but gets easily problematic because of trolls/gamethrowers.

I have 2 suggestions that can make being/playing with NE roles fun while not diminishing anyone else's ability to play.

My first suggestion is making NE game ending optional. That way people can continue playing without really being under the threat of NE roles. Of course, this would incentivise giving the NE roles their wins so each different NE should bring about a penalty to the crew. For example, Jesters and Executioners can kill those who voted for them/their target. Phantom is fine as is, it should be the only NE role that ends the game regardless of the setting. The new incoming Doomsayer role should kill those they guessed, and get the ability to guess other players freely. Although the drawback of this guessing is that if they fail to guess that player's role correctly, that player cannot be guessed by the Doomsayer for the rest of the game (only after winning, before winning the Doomsayer can guess players however much as they can based on its settings).

The first suggestion might bring about problems of its own, which would lead to inevitable kingmaking situations. My solution is to add an option called "Avoid Neutral Kingmakers". This option will disable Survivor and Guardian Angel from spawning, the main culprits behind kingmaking situations. Jesters already die upon achieving their objective but can't haunt anyone with this setting turned on. Executioners and Doomsayers will die at the end of the meeting after achieving their objective. Once again, Phantom is left unaffected as it's a pretty perfect NE role for its unique type (aka winning after death).

When an NE role wins, they will be added to the list of winners at the end of the game.

I wrote quite the essay here, but I hope this gets added as it'll improve the quality of games by so much more. If there are potential issues that I've not figured out yet, lmk so I can fix them by editing the suggestion/adding more to fix said issues.

**Comment by eDonnes124** [comment]
This is actually possible now, with v5.0.0 I've rewrote all the wincon code so it functions now and neutrals no longer sometimes win with crew (yes the bug which has been in the mod since the Slushie first made it), the format I've used to set it up can actually function this way with some slight alterations. I will definitely revisit this after I release v5.0.0.

**Comment by AlchlcDvl** [comment]
I see, can't wait for NE roles to be more fun. This would also solve the issue with games ending too early as well. Sometimes I just want longer games.

**Comment by AlchlcDvl** [comment]
my only issue with nes ending the game is that it's prone to gamethrowers. what prompted me to make this issue in the first place was me being sour over a game where i was obviously the executioner's target and the mayor just spam voted the hell out of me and ended the game. that game aside, it's only togglable so people can decide if they still want games to end fast.

my definition of a neutral role is that it's a role has its own goal that it will try to achieve, not matter the cost. by my definition there's 4 types of neutrals
- Benign: Has the capability to win with anyone as long as a certain condition is met
- Evil: Has a conflicting goal with other factions and is supposed to act as a deterrent (like jests and exe stop people from mindlessly voting, phantom increases the pace of the game and such)
- Killing: Have the capability to kill and their main goal is to kill everyone who can oppose them (aka crew, imps and other nks. nb and nes technically should not pose any threat to these roles)
- Neophyte (my own alignment that i'd like to add): These have the capability to convert others to their cause. neophyte at its most basic meaning means joining a different faith. this is where vamps (can even necro and whisp from cultist mode if neutral) would fall.
