### ISSUE TITLE
add an update for 2023.6.13 and helping to set the mod

### ISSUE THREAD

**Issue by TechDevOfficial** [eDonnes124/Town-Of-Us-R#154]
i can't play mod because i have a steam account and i have2023.3.28s but the account doesn't work. psl update

**Comment by TechDevOfficial** [comment]
some of youtubers can play the mod but how? can someone help me?

**Comment by AlchlcDvl** [comment]
the mod's not updated to 6.13 so it won't work

**Comment by TechDevOfficial** [comment]
no, for a lot of youtuers work like inooblive and tearless live

**Comment by AlchlcDvl** [comment]
they're playing a dev version that's not publicly available
