### ISSUE TITLE
Not able to launch

### ISSUE THREAD

**Issue by Christuba1643** [eDonnes124/Town-Of-Us-R#158]
I have done every step to download the mod but every time i try to launch it crashes

**Comment by whichtwix** [comment]
the mod doesnt work on the latest version so youll have to be on 6.27 firstly

only steam can do it tho, go to steam, rightclick among us, properties,betas, select public previous, then reinstall game

if it still crashs show your among us folder

**Comment by Christuba1643** [comment]
ok i fixed it
