### ISSUE TITLE
Mayor Issue 2.4.0

### ISSUE THREAD

**Issue by apacrep** [eDonnes124/Town-Of-Us-R#16]
When mayor vote comes up, It doesn't have abstain button. Both buttons say vote.

**Comment by whichtwix** [comment]
the abstain button was removed, you now recieve the extra vote when you skip

**Comment by apacrep** [comment]
I understand that. It's just very confusing for people why not remove it and when you hit bottom vote button it abstains.

**Comment by whichtwix** [comment]
thats...what was done
