### ISSUE TITLE
please add support for purchased hats to show in the hat menu.

### ISSUE THREAD

**Issue by spinmastercodes** [eDonnes124/Town-Of-Us-R#161]
Dont get me wrong, the custom hats are cool....its just that alot of them dont feel very among us like, and some cover up the entire color of the character, and theres only a handful of vanilla cosmetics available, could you either make all hats show, or make a separate version without custom hats?

**Comment by fariparedes** [comment]
I'm in favor of all purchasable items showing in the customization menu.

**Comment by whichtwix** [comment]
that would be against innersloth's mod policy, 

> Don’t distribute a mod that is not your own, and don’t distribute or sell direct paid copies of the Among Us IP itself, [policy](https://www.innersloth.com/among-us-mod-policy/)
those purchaseable items would be IP
