### ISSUE TITLE
[Suggestion] add this as a steam mod for among us, like the original

### ISSUE THREAD

**Issue by spinmastercodes** [eDonnes124/Town-Of-Us-R#162]
i think that would be great!

**Comment by JeanAU** [comment]
you mean publish an Launcher in steam to Launch TownOfUs with AU ?

**Comment by MyDragonBreath** [comment]
To do this it costs the steamworks direct fee (too my current knowledge), and the time and effort it takes to get the mod functioning through steam. As of current this is not a priority, and we do not have the funding.
