### ISSUE TITLE
Keyboard inputs not registering.

### ISSUE THREAD

**Issue by Itookthenuggets** [eDonnes124/Town-Of-Us-R#164]
Playing on Epic Games, attempted to reinstall already but problem hasn't fixed.
Moving through mouse inputs doesn't work either, although I can still access the settings menu.

**Comment by whichtwix** [comment]
your likely on the latest version, the mod isnt working on it rn and have to wait for a update

**Comment by Itookthenuggets** [comment]
Aight, thanks for letting me know
