### ISSUE TITLE
Hi I have a little problem with the town of us because when I get killed I can't see who killed me when someone kills someone during a meeting or reporting a body I can't see how many people died and I can't kill with every role please contact me and help me have a nice day :)

### ISSUE THREAD

**Issue by KrZys201120** [eDonnes124/Town-Of-Us-R#169]
Hi I have a little problem with the town of us because when I get killed I can't see who killed me when someone kills someone during a meeting or reporting a body I can't see how many people died and I can't kill with every role please contact me and help me have a nice day :)

**Comment by whichtwix** [comment]
what version of mod and game do you have, and which roles cant you killwith?

**Comment by KrZys201120** [comment]
Town of us 5.0.1 all roles cant kill

**Comment by KrZys201120** [comment]
V 2023.6.27s among us public previous

**Comment by whichtwix** [comment]
hmm ok, so first open your game, play some games, try killing etc, whatever is bugged, then go to your among us folder, go into bepinex, then drag and drop the logouput file here

**Comment by KrZys201120** [comment]
can you send a screenshot how to do it?

**Comment by whichtwix** [comment]
here, just instead of epic games itll be wherever your folder is
![15% complete 8_11_2023 3_53_14 PM](https://github.com/eDonnes124/Town-Of-Us-R/assets/91138333/94ac18e0-b591-4f7a-9ac9-25b91edd74d3)

**Comment by KrZys201120** [comment]
I'm sorry but I don't understand any of it because I'm Polish I translated this message 10 times and it came out a total failure XD could you show me what to do with logoutput?

**Comment by whichtwix** [comment]
here is in this textbox where you write your message, there is a sentence saying "attach files by dragging & dropping..", click it, itll open a small small window, find your logout through it, then click the open button, [here](https://www.youtube.com/watch?v=h6fOErvWIGI) at 1:42 it shows dragging and dropping too

**Comment by KrZys201120** [comment]
![20230811_152345](https://github.com/eDonnes124/Town-Of-Us-R/assets/139068951/3468e415-1932-44ac-a76a-b6e47cd94e2a)

**Comment by KrZys201120** [comment]
[LogOutput.log](https://github.com/eDonnes124/Town-Of-Us-R/files/12321927/LogOutput.log)
 good?

**Comment by whichtwix** [comment]
ok i checked it, theres nothing that could point toward the issue. theres also no indication of playing, you did do that right? asking incase

**Comment by KrZys201120** [comment]
I guess so, but I'll check

**Comment by KrZys201120** [comment]
Yes this is good

**Comment by whichtwix** [comment]
hold on are you playing public lobbies on north america, europe, or asia server?

**Comment by KrZys201120** [comment]
Modded eu

**Comment by KrZys201120** [comment]
Hello, are you there?

**Comment by whichtwix** [comment]
im not sure what else can be done
