### ISSUE TITLE
Connection issues 2.4.0

### ISSUE THREAD

**Issue by apacrep** [eDonnes124/Town-Of-Us-R#17]
People randomly disconnect on this version. We switched back to 2.3.4 and have had no issues now.

**Comment by eDonnes124** [comment]
The connection issues are due to the Innersloth servers and have nothing to do with the actual mod unfortunately.

**Comment by apacrep** [comment]
It's weird that issue doesn't exist in 2.3.4 lol

**Comment by whichtwix** [comment]
thats cuz 2.3.4 uses 6.30/7.20, those are the versions with no problms
