### ISSUE TITLE
Game no Work

### ISSUE THREAD

**Issue by PostmanPat1981** [eDonnes124/Town-Of-Us-R#176]
Whenever I or any of my friends try to host a game of the most recent update to this modpack. we will load in and then not be able to move click the settings icon or outfits icon. will also not allow friends to join. Just wanted to know if there was a fix in the works for this problem and if you didnt know bring light to the situation so a fix can be made thanks

**Comment by whichtwix** [comment]
if your steam you can go into steam, right click among us, properties,betas, select public previous, then reinstall the game

**Comment by PostmanPat1981** [comment]
I’ve done this a million times

**Comment by whichtwix** [comment]
well this is the solution, maybe check if your accidently selecting public beta, and when your on the branch steam shows among us[public previous], after that reinstall, if you make a copy of the game, make a fresh one too
