### ISSUE TITLE
Role Randomization is completely broken (same people get the same roles)

### ISSUE THREAD

**Issue by goaliedude3919** [eDonnes124/Town-Of-Us-R#177]
Title says it all really. The logic behind the random roles is completely broken. The same people will get the same handful of roles 90% of the time, which makes it really boring and lame. Whoever gets imposter the first time is probably going to be imposter like 75% of the time. Just go watch VODs from https://www.youtube.com/@DumbDogVOD if you don't believe me.

**Comment by LatGeek** [comment]
Also having this issue. It seems to even persist through different servers.

**Comment by AlchlcDvl** [comment]
servers have no influence on the role gen, it's just the generation logic that's a bit faulty with repetitions

**Comment by fariparedes** [comment]
The mod also has no impact on who is impostor. That's still decided by the base Among Us code, the mod just hands out roles to them.

**Comment by Patrykowy21** [comment]
If you set every role and modifier to 100% game gives everybody always same role.
