### ISSUE TITLE
I cant move

### ISSUE THREAD

**Issue by Allen-86521** [eDonnes124/Town-Of-Us-R#179]
I create an game and i cant move

**Comment by Gunx30** [comment]
You need to downgrade since the mod doesnt work on 7.12 but on 6.27 at the moment. If you dont know how to downgrade join the tour server the staff will help you there

**Comment by whichtwix** [comment]
if your steam you can do this, go to steam, rightclick among us, properties,betas, select public previous, then reinstall game
