### ISSUE TITLE
EPIC I CANT MOVE

### ISSUE THREAD

**Issue by REY11212** [eDonnes124/Town-Of-Us-R#185]
I CREATE SERVER AND CANT MOVE IN EPIC GAMES

**Comment by whichtwix** [comment]
you will need to downgrade in order to play, try this script, download it, then right click it and click "run with powershell", after its done reinstall the mod to where it installed the game 

https://cdn.discordapp.com/attachments/903796396757512272/1157631094548615208/DowngradeEpic.ps1?ex=65194f78&is=6517fdf8&hm=4ea696cccb5b9caef0a1fb5a6243acbb7f4d55a6fc596af5def63cff5179a071&

**Comment by REY11212** [comment]
> you will need to downgrade in order to play, try this script, download it, then right click it and click "run with powershell", after its done reinstall the mod to where it installed the game
> 
> https://cdn.discordapp.com/attachments/903796396757512272/1157631094548615208/DowngradeEpic.ps1?ex=65194f78&is=6517fdf8&hm=4ea696cccb5b9caef0a1fb5a6243acbb7f4d55a6fc596af5def63cff5179a071&
 
![Uploading изображение_2023-09-30_190703707.png…]()

**Comment by REY11212** [comment]
> you will need to downgrade in order to play, try this script, download it, then right click it and click "run with powershell", after its done reinstall the mod to where it installed the game
> 
> https://cdn.discordapp.com/attachments/903796396757512272/1157631094548615208/DowngradeEpic.ps1?ex=65194f78&is=6517fdf8&hm=4ea696cccb5b9caef0a1fb5a6243acbb7f4d55a6fc596af5def63cff5179a071&
 
![изображение_2023-09-30_190703707](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/0a61ce62-acaf-422f-9c91-5de7b6e47721)

**Comment by whichtwix** [comment]
you cant open the game using exe file, whereever you used the file you downloaded there will be a file that says "tou50.1..", you have to run that

**Comment by REY11212** [comment]
> you cant open the game using exe file, whereever you used the file you downloaded there will be a file that says "tou50.1..", you have to run that

![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/17473df0-0fef-4e48-8e9c-d3eff0105f2d)
There is it?

**Comment by whichtwix** [comment]
no, its prob in your downloads folder

**Comment by REY11212** [comment]
> no, its prob in your downloads folder

What i need to do?

**Comment by REY11212** [comment]
> no, its prob in your downloads folder

![Uploading image.png…]()

**Comment by REY11212** [comment]
> no, its prob in your downloads folder

![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/be0db40d-5bdb-41e9-b09c-b7f32ad903df)

**Comment by REY11212** [comment]
>

> no, its prob in your downloads folder

how I CAN CHANGE FOLDER?

**Comment by whichtwix** [comment]
go to your downloads folder, in your pic its the 3rd one on the left with the blue downwards arrow on it

> > you cant open the game using exe file, whereever you used the file you downloaded there will be a file that says "tou50.1..", you have to run that
> 
> ![image](https://user-images.githubusercontent.com/146541040/271772204-17473df0-0fef-4e48-8e9c-d3eff0105f2d.png) There is it?

go to your downloads folder, in your pic its the 3rd one on the left with the blue downwards arrow on it, or the one further down

**Comment by REY11212** [comment]
![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/f3a7bfb7-e5bb-45e9-adc0-ad551afa358e)
nothing

**Comment by whichtwix** [comment]
what folder did you put the powershell file in

**Comment by REY11212** [comment]
> what folder did you put the powershell file in

C:\Users\fafka\Games\AmongUs and I dont know how change it

**Comment by REY11212** [comment]
> what folder did you put the powershell file in

it was delivered by itself

**Comment by whichtwix** [comment]
> > what folder did you put the powershell file in
> 
> it was delivered by itself

what do you mean?

i guess go to the root of your c drive and in the search bar, search "legendary"

**Comment by REY11212** [comment]
> > > what folder did you put the powershell file in
> > 
> > 
> > it was delivered by itself
> 
> what do you mean?
> 
> i guess go to the root of your c drive and in the search bar, search "legendary"

powershell need launch with administrator?

**Comment by REY11212** [comment]
> > > what folder did you put the powershell file in
> > 
> > 
> > it was delivered by itself
> 
> what do you mean?
> 
> i guess go to the root of your c drive and in the search bar a little under top right, search "legendary"

![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/5ad653af-9b00-4ea8-8561-ee185fe751a7)
this?

**Comment by whichtwix** [comment]
> powershell need launch with administrator?
no, your au already downloaded correctly, it seems its turned a problem finding where ToU5.0.1-6.27.cmd got placed

hmm, quite strange it went all the way over there, ok so click the legendary icon and see if takes you there

**Comment by REY11212** [comment]
> > powershell need launch with administrator?
> > no, your au already downloaded correctly, it seems its turned a problem finding where ToU5.0.1-6.27.cmd got placed
> 
> hmm, quite strange it went all the way over there, ok so click the legendary icon and see if takes you there

![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/495238b9-df8c-4e76-be03-dd9073476419)

**Comment by whichtwix** [comment]
ok, here put in ```legendary launch 963137e4c29d4c79a81323b8fab03a40 --skip-version-check```

everytime you want to run this among us you downloaded youll have to open legendary and put this
can you show a pic of the folder c:\WINDOWS\System32, likely the cmd file is there then

**Comment by REY11212** [comment]
> legendary launch 963137e4c29d4c79a81323b8fab03a40 --skip-version-check

![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/4c83dc66-4f57-471f-a5a3-d62407627bea)
I launch it but I cant move

**Comment by REY11212** [comment]
> ok, here put in `legendary launch 963137e4c29d4c79a81323b8fab03a40 --skip-version-check`
> 
> everytime you want to run this among us you downloaded youll have to open legendary and put this can you show a pic of the folder c:\WINDOWS\System32, likely the cmd file is there then

![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/72465198-8d67-4b18-b8fa-0646d5f188e2)

**Comment by whichtwix** [comment]
hmm hold on then it went wrong somewhere, run the powershell script and take pics as it runs

**Comment by REY11212** [comment]
> hmm hold on then it went wrong somewhere, run the powershell script and take pics as it runs

![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/941d5a93-45f0-44d5-98c1-65ddf454bc67)

**Comment by REY11212** [comment]
![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/83f3ac75-e4d3-42a6-b5c0-4e0cad897ef5)

**Comment by REY11212** [comment]
![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/90dd237c-447c-46d4-be04-de132248dcac)

**Comment by whichtwix** [comment]
ye, click 'y'

**Comment by REY11212** [comment]
![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/60b4b23b-17b1-4b92-be6a-3f4c5c03c2a6)

**Comment by whichtwix** [comment]
ok try the legendary launch command i wrote earlier

**Comment by REY11212** [comment]
![image](https://github.com/eDonnes124/Town-Of-Us-R/assets/146541040/f252d1e2-9e57-4be0-a177-576da9fbd3ce)

**Comment by whichtwix** [comment]
uh enter it once then wait

**Comment by REY11212** [comment]
> legendary launch 963137e4c29d4c79a81323b8fab03a40 --skip-version-check

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE LETS GOOOOOOOOOOOOO

**Comment by whichtwix** [comment]
did it give 6.27?

**Comment by REY11212** [comment]
> did it give 6.27?

yes

**Comment by whichtwix** [comment]
ok, i saw you already put mod in that folder so it should be fine and youll be able to play, if you go to c:\WINDOWS\System32, the tou5.0.1.. . cmd file is prob there now hopefully, you can write 'ls' in powershell and itll show if its really there

**Comment by oraziotorre** [comment]
I think you need to create a step-by-step guide for this.

**Comment by whichtwix** [comment]
perhaps, i want to make sure the script is working first
