### ISSUE TITLE
(Question) will mod get updated to newest version?

### ISSUE THREAD

**Issue by Bartoxion** [eDonnes124/Town-Of-Us-R#187]
im wondering if mod will get updated to newest version because downgrading dont work for me (Im on epic)

**Comment by whichtwix** [comment]
there is no eta

however you can downgrade on epic
1. download this https://cdn.discordapp.com/attachments/903796396757512272/1157631094548615208/DowngradeEpic.ps1?ex=651bf278&is=651aa0f8&hm=6daf354b69ea3917c33370a35af5b4ca6c470911991a85e888360def7540a21c&
2. right click it in your downloads and then click "run with powershell"
3. click 'y' the couple of times it asks and follow the text in red background
4. install tou to that folder
5. a "tou5.0.1-6.27.cmd" file is going to be in your downloads, use that to open downgraded game

**Comment by AlchlcDvl** [comment]
it just got updated
