### ISSUE TITLE
Can't use Submerged with this mod

### ISSUE THREAD

**Issue by PhilD95** [eDonnes124/Town-Of-Us-R#193]
I can't use the Submerged Map mod with Town of Us R. With TheOtherRoles Submerged can be used after clicking a button in the Among Us Startup Screen. Is there a way to fix this?

**Comment by whichtwix** [comment]
download submerged here https://github.com/SubmergedAmongUs/Submerged/releases/download/v2023.8.2/Submerged.dll, then copy paste the dll to your au folder/bepinex/plugins
