### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by townofus** [eDonnes124/Town-Of-Us-R#21]
among us town of us its works perfectly fine in 2.4.1 but the thing is when i or someone else wins the game the win does not show for me so i have to leave and join back

**Comment by disabledworx** [comment]
It's a vanilla bug. Vanilla players as well as modded players are all reporting it on the TownOfUs server as well as the Innersloth server but I will hand this off to others to see if I'm right

**Comment by townofus** [comment]
ok

**Comment by townofus** [comment]
YAY I UNINSTALLED THE GAME AND INSTALLED IT AND IT WORKED
