### ISSUE TITLE
Discord link being invalid

### ISSUE THREAD

**Issue by Knoface** [eDonnes124/Town-Of-Us-R#215]
I really want to play town of us but i need the discord to do so but the link is invalid so can i get some help

**Comment by whichtwix** [comment]
https://discord.gg/9DqNQuAD, the link in the readme seems to be fine though

**Comment by Knoface** [comment]
huh thats weird it still says its invalid and i know im not banned because ive never been on the discord maybe its a problem with my browser or something i'll look into it

**Comment by Knoface** [comment]
ok i did it with the discord app and that worked
