### ISSUE TITLE
Feature Request: Additional options for kill cooldowns

### ISSUE THREAD

**Issue by andrew-vant** [eDonnes124/Town-Of-Us-R#22]
My regular AU/ToU group has an issue with "paranoia buttons" -- that is, people buttoning just to reset the impostor's kill cooldown. While we could forbid doing so on the honor system, that's hard to remember and hard to police. We'd prefer to remove the incentive.

Would it be possible to add options controlling the circumstances under which cooldowns reset? For example, the following could be checkbox settings, each defaulting to "on" (the current behavior):

* [x] Body reports reset kill cooldowns
* [x] Emergency button resets kill cooldowns

A more flexible variant might integrate this into the cooldown-duration settings, somewhat like this:

* Kill cooldown (default): 30s
* Kill cooldown (game start): 10s
* Kill cooldown (murder): Use Default
* Kill cooldown (bodyreport): 15s
* Kill cooldown (button): Leave Unchanged

Or perhaps even allow deltas:

* Kill cooldown (button): +5s (that is, add 5s to the current cooldown, perhaps capped to the default value)

I don't know to what extent any of this is possible to mod; take the specific suggestions with salt.

**Comment by whichtwix** [comment]
let edonnes know on our disc server
