### ISSUE TITLE
feature request: arrows for amnesiac

### ISSUE THREAD

**Issue by DeltaNedas** [eDonnes124/Town-Of-Us-R#23]
(im assuming that 2.5.0 is a private version, saw it on jardon's stream)

lots of players think amnesiac would be easier with arrows pointing to dead bodies, similar to the vulture from the other roles.

**Comment by whichtwix** [comment]
ive put the idea on our disc, if yyou have other ideas send them there

**Comment by eDonnes124** [comment]
Added on v2.6.2
