### ISSUE TITLE
Not getting the latest version

### ISSUE THREAD

**Issue by Tabbycat9** [eDonnes124/Town-Of-Us-R#236]
I have tried multiple times to redownload the mod to get the latest version, but my games says I don't have the latest version of the mod.

**Comment by whichtwix** [comment]
do you have the latest version of the game too, 2024.3.5

**Comment by Tabbycat9** [comment]
I downloaded the version it said but it says I have 2023.11.28 for some reason

**Comment by whichtwix** [comment]
well then it you have to update among us, check that your not public previous branch, and remake tou copy if you have 1

**Comment by Tabbycat9** [comment]
my game has said it is up to date I have uninstalled and reinstalled the game, but it still says the something after the game same thing

**Comment by whichtwix** [comment]
did you check your betas too, right lick among us, properies,betas, make sure your on none
