### ISSUE TITLE
Feature Request: Executioner Target Label

### ISSUE THREAD

**Issue by TonyGamer** [eDonnes124/Town-Of-Us-R#24]
It would be nice if dead players could see who the executioner's target is through a small symbol, much like how lovers have a small heart symbol next to their name. I was thinking the symbol should be an axe or something like that

**Comment by whichtwix** [comment]
ive put the idea on our disc, if yyou have other ideas send them there

**Comment by eDonnes124** [comment]
This was added a while ago just forgot to close issue.
