### ISSUE TITLE
I can't launch after adding the mod

### ISSUE THREAD

**Issue by GalaxySaturn** [eDonnes124/Town-Of-Us-R#243]
5.0.3 was okay, but 5.0.4 after showing the sign of innersloth it will become dark and a "MOD" sign on the right upper corner
<img width="685" alt="35c672858b515250" src="https://github.com/eDonnes124/Town-Of-Us-R/assets/78467111/d92022f7-0013-47b9-bbef-c6dc9c43d51f">
just like this

**Comment by whichtwix** [comment]
are you sure your on the latest among us version

**Comment by GalaxySaturn** [comment]
> are you sure your on the latest among us version

yes of course

**Comment by whichtwix** [comment]
you can try going to C:\Users\you\AppData\LocalLow\Innersloth\Among Us and deleting everything, then retry opening
