### ISSUE TITLE
Vampire and Impostor 2-player endgame can't be won by impostor

### ISSUE THREAD

**Issue by taelspinner** [eDonnes124/Town-Of-Us-R#247]
Because of this line of code:
https://github.com/eDonnes124/Town-Of-Us-R/blob/eddc89eda75251541e0e9b82d0c9b40df6ea8aff/source/Patches/Roles/Vampire.cs#L41

It's not possible for the impostor to win in a game that's down to the final 2, impostor vs Vampire. If the impostor kills the Vampire, they will lose, despite being the sole surviving killer, because the logic does not check to ensure that *a Vampire is still alive* in that situation.

**Comment by eDonnes124** [comment]
I checked it and it seems to work fine.
