### ISSUE TITLE
Fix this mod

### ISSUE THREAD

**Issue by MrKaratio1337** [eDonnes124/Town-Of-Us-R#257]
My friends have Among Us on steam and I want to play with their, but I have Among Us on Epic Games. The problem is version of mod. In steam is working version 5.0.3, but on Epic Games is working version 5.0.4. Can u fix this?

**Comment by whichtwix** [comment]
there is no problem with the mod right now, they should update to 5.0.4, your fine, they should check that their on latest among us version and make sure their on none for betas
