### ISSUE TITLE
pls remove modded handshake and 2024.6.4 update

### ISSUE THREAD

**Issue by jiggusuperking** [eDonnes124/Town-Of-Us-R#282]
update among us to 2024.6.4
add vanilla server support
bro it just roles pls remove handshake
no custom maps and no custom skins and hats and pets
idoits only do this only mods with roles
unmodded players can see role description
i accept this if there custom maps and skins and hats and pets
pls remove modded handshake
idoit developer
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods

immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods

immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods

immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods

immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods

immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
immediately i dont see this modded hanshake only in mods
and i never see this modded handshake again

**Comment by jiggusuperking** [comment]
> are you crazy or whatt ?????????? don't spam
i am not spammming its virus has came

**Comment by jiggusuperking** [comment]
> are you crazy or whatt ?????????? don't spam
i am not spammming its virus has came

**Comment by lekillerdesgames** [comment]
wtf is happening Ive seen multiple issues like this bro is destroying the poll requests
