### ISSUE TITLE
Reactor Download?

### ISSUE THREAD

**Issue by lowelhere** [eDonnes124/Town-Of-Us-R#286]
hi! sorry! my friend recently tried to join my lobby but it said she was kicked on her end. On my end, the chat said she didn't have reactor downloaded and therefore couldn't enter. 

Did I install the mod incorrectly?

edit: spelling and grammar

**Comment by whichtwix** [comment]
They wlso need to install the mod

**Comment by lowelhere** [comment]
> They also need to install the mod

Oh, so it's unavailable to mobile users? That kinda sucks! But thanks for the quick reply!

**Comment by whichtwix** [comment]
delete the bepinex and dotnet folder, steamappid.txt, doorstop, winhttp.dll
