### ISSUE TITLE
Game crashing with mod

### ISSUE THREAD

**Issue by BadJuiceIsCool** [eDonnes124/Town-Of-Us-R#287]
Everytime I open AmongUs with the mod, it crashes on the loading screen. Is it because the mod version is wrong with the among us version?

**Comment by whichtwix** [comment]
yes you need to downgrade the game, steps are at the bottom of steam installation and epic installation section

**Comment by BadJuiceIsCool** [comment]
I followed all the steps, but when I tried to create a lobby, it just became a black screen. And when I pressed the black screen, it just goes back to the main screen.
