### ISSUE TITLE
game creation

### ISSUE THREAD

**Issue by mcschtapp** [eDonnes124/Town-Of-Us-R#288]
the mod is downloaded and open. however when i go to create a game to confirm its working the screen goes to black and never loads. In the initial create lobby it seems setting are un-interactable not sure if that is a cause of something.
![Capture](https://github.com/eDonnes124/Town-Of-Us-R/assets/174223416/a0e4bbdc-9390-4318-807a-549230ae1a41)

**Comment by mcschtapp** [comment]
Screenshot after hitting confirm on the previous screenshot

 ![Capture](https://github.com/eDonnes124/Town-Of-Us-R/assets/174223416/0a9d7c62-c710-419f-b255-380af6b9ad90)

**Comment by whichtwix** [comment]
go to appdata/locallow/innersloth/among us and delete settings.amogus
