### ISSUE TITLE
Game crashing with mod

### ISSUE THREAD

**Issue by Venexic** [eDonnes124/Town-Of-Us-R#290]
I'm guessing this is due to this mod being compatible with a previous version of Among Us and I'm using the most recent version. I really did enjoy this mods with my friends (them being on Xbox) and would love for it to be updated so we can have fun with it again...

**Comment by whichtwix** [comment]
you cant play this mod on xbox or mobile

**Comment by Venexic** [comment]
oh sorry it was Town of Us Enhanced we played, only the host needs the mod and I'm on PC
