### ISSUE TITLE
Mod crashes

### ISSUE THREAD

**Issue by DesiredWolf** [eDonnes124/Town-Of-Us-R#294]
I did everything right, even watched a video, there is 1 folder called "dotnet" which crashes the mod. When I delete the folder, the mod doesn't work but if I still include it, it just crashes. Anyone know the issue to this? I play on steam (pc) if that info is required

**Comment by whichtwix** [comment]
the dotnet folder is a required folder. go to steam, right click au, properties, betas, select public previous, then reinstall game, then go appdata/locallow/innersloth/among us and delete settings.amogus.
