### ISSUE TITLE
please make Town-Of-Us-R a new version for v2024.6.18 

### ISSUE THREAD

**Issue by BlurryFaceleever** [eDonnes124/Town-Of-Us-R#296]
we all want it. (this really isn't an " issue " I just want to play on the new version)

**Comment by GameTechGuides** [comment]
The developers are working hard on the newest version, so please be patient. There are many changes in the codebase. Thank you for your patience. @BlurryFaceleever

**Comment by BlurryFaceleever** [comment]
good to know. Thanks!
