### ISSUE TITLE
stalk button as vampire

### ISSUE THREAD

**Issue by olokolo0331** [eDonnes124/Town-Of-Us-R#301]
![Zrzut ekranu (717)](https://github.com/user-attachments/assets/85147738-a752-4965-b228-5556a968ddb2)
![Zrzut ekranu (718)](https://github.com/user-attachments/assets/44d1f491-dd41-4103-9332-db2988c3ba44)
I was hunter and I clicked 'stalk' on somebody. When stalk duration was 4, someone gave me vampire. In all next rounds and meetings i had stalk button with 4 duration

**Comment by ItzLoonie** [comment]
Appears to just be an error with clearing buttons the player shouldn't have.
