### ISSUE TITLE
Mod not installing

### ISSUE THREAD

**Issue by Amongme233** [eDonnes124/Town-Of-Us-R#302]
I downloaded the mod on my phone but when I clicked on the zip file after I downloaded it it wouldn't show a screen, so I thought maybe the mod had already been installed but it wasn't, can you please help me with this?

**Comment by whichtwix** [comment]
cant play on phone

**Comment by Amongme233** [comment]
Okay, but can you get an among Us mod like this for phone on Happymod or something

**Comment by whichtwix** [comment]
phones cant install many mods themselves, you can find discord servers for mods that have town of host in their name, find a lobby code, and join those
