### ISSUE TITLE
Not able to start lobby

### ISSUE THREAD

**Issue by lucien29** [eDonnes124/Town-Of-Us-R#305]
I am on public previous and i dragged the mod pack into a copy of the among us folder, the mod runs as expected and I have everything but I am not able to start a lobby the game freezes on it. thank you for your time

**Comment by whichtwix** [comment]
go to appdata/locallow/innersloth/among us and delete settings.amogus

**Comment by lucien29** [comment]
Sorry but I have another issue now, when I try to play the mod it will not sign in, and forces me to play on offline

**Comment by lucien29** [comment]
Nevermind I have fixed it, Thank you!
