### ISSUE TITLE
[SUGGESTION] Aurial shouldn't see First Death Shield

### ISSUE THREAD

**Issue by yannl35133** [eDonnes124/Town-Of-Us-R#307]
The Aurial can see the First Death Shield, which means they can immediately know who that person is.
This seems to go against the spirit of this role, hence the suggestion.

**Comment by yannl35133** [comment]
Where was this implemented or why did you not do it? I can't see any recent commit.

**Comment by eDonnes124** [comment]
Aurial has had a rework and the update should be out tomorrow (I'm hoping).
