### ISSUE TITLE
Game Shuts Down after Launching

### ISSUE THREAD

**Issue by AwaiHono** [eDonnes124/Town-Of-Us-R#308]
Hello,
after Launching the Game, the Innersloth Logo appears, then it blackscreens and shuts down repeatedly.
Im on public previous Beta(windows 11 Steam), tried to deinstall and reinstall the Game and the mod multiple Times, deleted the Innersloth folder in Appdata\LocalLow and still couldnt fix the problem, does anyone know a fix for that?
I also tried to deactivat Firewall and/or Antivirusand it didnt help.

**Comment by whichtwix** [comment]
use public beta branch now

**Comment by AwaiHono** [comment]
That fixed it, thank you very much.
