### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Dashcam-footage33** [eDonnes124/Town-Of-Us-R#310]
My Amongus isnt working. I have restated the application (Modded) And restarted my computer
![Screenshot 2024-09-16 131617](https://github.com/user-attachments/assets/79760381-7389-4320-8811-92455ab6d86e)

**Comment by Dashcam-footage33** [comment]
the picture is what it looks like

**Comment by whichtwix** [comment]
go to c:/users/you/appdata/locallow/innersloth/among us and delete settings.amogus
