### ISSUE TITLE
Downgrade Alert Message

### ISSUE THREAD

**Issue by CYCLOLCYC** [eDonnes124/Town-Of-Us-R#313]
When I open ToU-R v5.1.0, it says that I have to downgrade my among us to v2024.9.4 even though I already have v2024.9.4 installed. Is there any way to fix this?

**Comment by s1mplydeci** [comment]
this also seems to be happening to a majority of people installing the mod. 
![Capture](https://github.com/user-attachments/assets/58302a73-ff39-4d53-829e-303cd0b753d3)

**Comment by eDonnes124** [comment]
Hotfixed v5.1.1
