### ISSUE TITLE
permanent black screen on load (on 5.1.1s download)

### ISSUE THREAD

**Issue by s1mplydeci** [eDonnes124/Town-Of-Us-R#314]
permanent black screen on load but mod icon is seen top right. - sorry donners :(

settings.amogus is deleted ( i retried whole folder no different)
not working for anyone downloading 5.1.1s 
(someones sat on it for 10mins)

![image](https://github.com/user-attachments/assets/23fb2977-2c6a-45a8-8e9a-5d1d6f2b8f78)

**Comment by FangkuaiYa** [comment]
The author seems to have made changes to something and there seems to be a problem

**Comment by eDonnes124** [comment]
Should be fixed if you relaunch, sorry for the inconvenience.
