### ISSUE TITLE
Error when a 10th person joins

### ISSUE THREAD

**Issue by TrekkieGal** [eDonnes124/Town-Of-Us-R#32]
Several of the people in our group have been having a problem when playing with a group of 10 or more people.  If we're the 10th person to try to enter the lobby, we can't get in and the people who are already in the lobby see a Player Clone.  If we're already in the lobby when 10th person joins, we get kicked out.

**Comment by whichtwix** [comment]
id try these:

find a public game, refresh the page and switch back to the private server and paste the lobby code with CTRL + V. This seems to work.

paste the code, do not type, and use the arrow and not enter key
