### ISSUE TITLE
v5.1.2 WIP Build

### ISSUE THREAD

**Issue by eDonnes124** [eDonnes124/Town-Of-Us-R#324]
Fixed:
- Fixed Soul Collector Passive Soul Collection after Death
- Removed the ability to type messages beginning with "/"
- Fixed Jailor being able talk to Jailee once dead
- Fixed Arsonist Cooldown being removed when all Imps dead instead of when other NKS/Imps are dead
- Fixed End Game Scenario with Vampires/Lovers
- Fixed Impostors not seeing their dead teammate
- Fixed Hypnotised players seeing Revealed Roles with incorrect names
- Fixed Shy visibility consistency (transport/disperse/kill)

To Do:
- Transporter Transport with Level Impostor
- Role Viewing when someone joins (lobby)
- New AU version compatibility

If there is a bug I am not aware of please reply to this issue and I might fix it before next release.
I am also considering adding a setting for Hunter for the old retribution feature although I want this patch to be mainly focused on bug fixes.

**Comment by Lolro16** [comment]
how long will it take to release?

**Comment by eDonnes124** [comment]
Now.
