### ISSUE TITLE
Question: How do i turn it back to normal among us

### ISSUE THREAD

**Issue by LolISkriptIsCool** [eDonnes124/Town-Of-Us-R#33]

**Comment by NinjaAUM** [comment]
IF you installed it on steam or Epic folder do:
(Steam) Go on file explorer, in the path type `C:\Program Files (x86)\Steam\steamapps\Among Us` and delete anything BepInEX/tour related. 
(Epic Games) Go on file explorer, in the path type `C:\Program Files\Epic Games\Among Us` *i think, and delete anything BepInEX/tour related.
