### ISSUE TITLE
ghosts ignore tasks

### ISSUE THREAD

**Issue by Psh3m0** [eDonnes124/Town-Of-Us-R#335]
where is this option in game

**Comment by eDonnes124** [comment]
I didn't work on this, someone else did, I don't think this is something needed in the game.

**Comment by Psh3m0** [comment]
so why is it there 
![image](https://github.com/user-attachments/assets/4dae87a6-edf3-46a8-9d18-e665fad428f8)

**Comment by eDonnes124** [comment]
I didn't add it, wasn't modding at the time so I have no answer for this.
