### ISSUE TITLE
Game can't end because a player can't complete a task

### ISSUE THREAD

**Issue by miaklotheprogrammer** [eDonnes124/Town-Of-Us-R#338]
Player's pov expieriencing the issue:
(on both images look on the player "MTX")
https://cdn.discordapp.com/attachments/1319997737063940137/1321966278994296856/image.png?ex=676f2889&is=676dd709&hm=f5d144405202eda785c99452553d61817ad730782fd941e2f1378b3a2ece42bf&
Another player's Pov:
https://cdn.discordapp.com/attachments/1319997737063940137/1321966279393021953/image.png?ex=676f2889&is=676dd709&hm=ce59c17dc0b632998a07042bd085992d916451b863ffb951c0f847182624be09&

**Comment by miaklotheprogrammer** [comment]
Player's pov expieriencing the issue:
https://cdn.discordapp.com/attachments/1319997737063940137/1321966278994296856/image.png?ex=676f2889&is=676dd709&hm=f5d144405202eda785c99452553d61817ad730782fd941e2f1378b3a2ece42bf& 
Another player's Pov:
https://cdn.discordapp.com/attachments/1319997737063940137/1321966279393021953/image.png?ex=676f2889&is=676dd709&hm=ce59c17dc0b632998a07042bd085992d916451b863ffb951c0f847182624be09&

**Comment by eDonnes124** [comment]
"This content is no longer available." Is all I see. I assume it's the water wheel bug, that's vanilla and I don't know how to fix that, we modify nothing to do with the water wheel unfortunately.
