### ISSUE TITLE
2.5.1

### ISSUE THREAD

**Issue by Craudion** [eDonnes124/Town-Of-Us-R#36]
the game thinks im hacking every time there is 3 people, fix this bug, thanks

**Comment by whichtwix** [comment]
we cant fix that bug, anything that mods the game is considered hacking, there is only 1 fix to play on a custom server such as ours, tou master

**Comment by apacrep** [comment]
You could fix the bug because the issue only happens when someone kills bait. Even happens on tou master. We have to turn off bait and no more issues.

**Comment by whichtwix** [comment]
well why turn it off when you could play with it and a minimal change of selecting a different server
