### ISSUE TITLE
TOU 2.5.1 Multiple issues

### ISSUE THREAD

**Issue by apacrep** [eDonnes124/Town-Of-Us-R#38]
Some imposters can't kill in meeting as assassins' randomly, vitals move from lab to office randomly, you have to disable bait in order to not get kicked for cheating. Dev 11 had none of these issues so not sure how the game went backwards in development.

**Comment by whichtwix** [comment]
wdym vitals move randomly, are you sure you just dont have better polus. the bait problem isnt on master theres no anti cheat to ban you. are the some imps ones that were amned

**Comment by eDonnes124** [comment]
First things are options for assassin, second thing is Better Polus, yes the problem with Bait is a bug.
