### ISSUE TITLE
v2.3.2 What has been updated?

### ISSUE THREAD

**Issue by mingyuxinli** [eDonnes124/Town-Of-Us-R#5]
Please tell me where to see the update announcement.I can not find it anywhere

**Comment by eDonnes124** [comment]
You can see all the changes in the changelog which is below the releases. Discord link is also on the github: https://discord.com/invite/ugyc4EVUYZ.

**Comment by mingyuxinli** [comment]
> 
> 
> 您可以在版本下方的更改日志中看到所有更改。 Discord 链接也在 github 上： : [https //discord.com/invite/ugyc4EVUYZ ](https://discord.com/invite/ugyc4EVUYZ)。

thank u very much
