### ISSUE TITLE
Most Major Bugs:

### ISSUE THREAD

**Issue by eDonnes124** [eDonnes124/Town-Of-Us-R#52]
Host can hear every individual Mayor vote.
The Swapper can swap a dead player that was assassinated that meeting.
If the Miner places vents in certain spots on Polus and Airship, they are invisible.
If the Undertaker drags a body to certain spots on Polus and Airship, they are invisible (but still reportable).
Amnesiac turned Poisoner can’t poison anyone.
After either the Camouflager uses their camouflage ability or after camouflaged comms, if a Morphling or Glitch morphed during this time and exits the camouflaged period still morphed, everyone else sees them with the incorrect name.
If someone disconnects when a Phantom/Haunter is active (unclicked) EVERYONE loses their abilities (except Impostors killing).

**Comment by apacrep** [comment]
When poisoner attacks shielded person it immediately kills them and breaks shield at same time.
