### ISSUE TITLE
Show roles to dead people

### ISSUE THREAD

**Issue by jasondorjeshort** [eDonnes124/Town-Of-Us-R#56]
I strongly feel this should be settable as a percentage: set it to 80% to have an 80% chance rolled at the start of the game that dead people can see roles.  This could be EXTREMELY useful as a sustainable tool against stream sniping, since snipers in a lobby would struggle to maintain consistent play as this setting changes.  And of course it should be easy and nonintrusive.

**Comment by whichtwix** [comment]
at the point of stream sniping it should just be considered cheating and people should try to figure out who it is and ban them. being a % just hurts the fair players

**Comment by jasondorjeshort** [comment]
Absolutely.  But having it as a percentage is a direct tool to enable figuring out who it is.  You'll see a different level of performance in the same lobby in games with and without dead roles shown.
