### ISSUE TITLE
The Guardian Angel is Very Pointless if The Player You Have to Protect is One of The Imposters That Have a Kill Button.

### ISSUE THREAD

**Issue by Bj007pro** [eDonnes124/Town-Of-Us-R#72]
As the Guardian Angel the main point is to follow who you need to protect right?

There's not bloody point to follow an Imposter that has a kill button because they'll most likely kill you instantly, or kill you instantly because they think you're The Glitch.

Make it so that this doesn't happen, please? Thanks! <3

**Comment by YellowC1** [comment]
Twix is right tbh xD
