### ISSUE TITLE
when is new version coming out?

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [eDonnes124/Town-Of-Us-R#75]
for the lastest ver of among us

**Comment by MrWeasel1000** [comment]
> for the lastest ver of among us

TownOfUs v3.0.1 works with the latest version of Among Us. The TownOfUs Reactivated Discord is the best place to play and ask

**Comment by mezzomix23** [comment]
I tried 3.0.1 with version 2022.4.19e, it does not work, unless I'm doing something wrong.

**Comment by MrWeasel1000** [comment]
> I tried 3.0.1 with version 2022.4.19e, it does not work, unless I'm doing something wrong.

Please join the Discord Server (if you haven't already) and ask the team if you have

**Comment by mezzomix23** [comment]
I'm there already, but in which channel/section should I ask exactly?

**Comment by MrWeasel1000** [comment]
> I'm there already, but in which channel/section should I ask exactly?

Open a support ticket so they may help.
