### ISSUE TITLE
Among Us version 2022.4.19

### ISSUE THREAD

**Issue by chillultimated** [eDonnes124/Town-Of-Us-R#78]
Among Us was updated to version 2022.4.19, but Town of Us-R runs only on v2022.3.29, so I gues that move Town of Us-R to 2022.4.19 would be nice.

**Comment by Hunwer8796** [comment]
How do I play

**Comment by MrWeasel1000** [comment]
> How do I play

You can join the TownOfUs-R Discord Server (linked in the README) where there are games going on everyday and it's both VC and Non-VC.
