### ISSUE TITLE
I can't kill with Town-Of-Us (ToU.v3.1.0.zip) in Among Us v2022.3.29s

### ISSUE THREAD

**Issue by tedomedo** [eDonnes124/Town-Of-Us-R#79]
Is there something in settings? Without ToU i can kill. The same with ToU.v3.0.0 - killing not possible. 
I don't have Steam or Epic games.  I downloaded the game "somewhere", installation wasn't needed. I copied and pasted everything from folder tou.3.1.0 .zip into Game folder.

**Comment by whichtwix** [comment]
that would be called pirating the game, which is illegal, and as such we cant give support then

**Comment by tedomedo** [comment]
And what would be your reply, if i posted that i installed it using Steam? Just theoretically?
