### ISSUE TITLE
New role (Imitator)

### ISSUE THREAD

**Issue by Maikiz** [eDonnes124/Town-Of-Us-R#8]
Imitator (Crewmate Role)
Each round/game receives a random ability of a deceased peaceful player, if there are any.
If Shifter takes the role of Imitator, then Shifter gets the role of a random dead peaceful player.

**Comment by apacrep** [comment]
why are these roles not in mod?

**Comment by eDonnes124** [comment]
All I'll say is after a year there is a reason why this suggestion is being closed.
