### ISSUE TITLE
Stuttering on Windows 11

### ISSUE THREAD

**Issue by madixo** [eDonnes124/Town-Of-Us-R#81]
[issue-933259845](https://github.com/slushiegoose/Town-Of-Us/issues/234#issue-933259845)

This issue describes it well. I have lag spike every approximately one second. Vanilla game isn't lagging at all.

CPU: Intel i5-9400F
GPU: MSI RTX 2060 VENTUS OC 6GB
RAM: 16GB
MOBO: MSI B360M Bazooka

**Comment by eDonnes124** [comment]
We actually talked about this recently, -H thinks he knows the issue and we're not entirely sure how to fix it. Apparently it's that Among Us likes multiple CPUs while Town Of Us does not, and vice versa.

**Comment by madixo** [comment]
Seems about right, tried to change affinity for among us to one core, and it was smooth for the most part, but there were bigger lag spikes during loading and I was having audio issues, so doesn't seem like viable fix.

**Comment by ItsTheNumberH** [comment]
The best solution I can offer thus far is changing affinity to CPUs 1 and 2 (Not 0 and 3). It still has the occasional micro-stutter, but is a lot better.
Obviously, not exactly a viable solution and is specific to my machine so won't work for everyone. But might help for now.

**Comment by GaranceF** [comment]
It's not just Windows 11, it's also in Windows 10. And it's been here even before ToU-R, it's an inherited bug from Town of U.

I thought it was just bad hardware performance, but it happens to a lot of different builds, especially higher end hardware.

The thing I can't understand is why it happens to some builds and not others.

If you ever find a solution don't hesitate to put it here.

**Comment by GaranceF** [comment]
@ItsTheNumberH 
Thanks for your help, your solution works perfectly (for now at least) !
👍
