### ISSUE TITLE
Haunter being clicked in office while in medbay

### ISSUE THREAD

**Issue by getruind** [eDonnes124/Town-Of-Us-R#82]
Saw this today on a stream, no idea what causes it but figured the clips might help.

https://clips.twitch.tv/SteamyChillyHabaneroEagleEye-BapmCRTYvRMhZdbh

https://clips.twitch.tv/GleamingSmallStingrayThunBeast-3IrIfHENjsi5k40i

**Comment by getruind** [comment]
https://clips.twitch.tv/FurrySpineyJayTwitchRPG-4ndhRW0mBgwYIZ_A
https://clips.twitch.tv/SaltyAgreeableLatteFrankerZ-mckkqPtVR3HkqAps
again

**Comment by whichtwix** [comment]
yeah theres currently a bug with haunter and phantom, youll see them in a place they arent, but the hitbox is still in the older spot so they can be clicked
