### ISSUE TITLE
v3.2.0 "Not Found"

### ISSUE THREAD

**Issue by brycewiedemeier** [eDonnes124/Town-Of-Us-R#85]
Unsure as to why, but the listed 3.2.0 version of the mod gives a 404 error instead of bringing to a download page.

**Comment by whichtwix** [comment]
the zips were changed so it was prob that thew link in the release table wasnt updated, do directly from releases instead https://github.com/eDonnes124/Town-Of-Us-R/releases/download/v3.2.0/ToU.v3.2.0s.zip

**Comment by eDonnes124** [comment]
Sorry just fixed that.
