### ISSUE TITLE
Discord for suggestions

### ISSUE THREAD

**Issue by CraftManiakpl** [eDonnes124/Town-Of-Us-R#87]
I have a proposal to open a discord for Town of Us players. Beyond the possibility of playing together, you would be able to propose a role on a special channel according to set criteria. And if the creators do not have ideas that they would enter such a channel and inspire the ideas of players.

**Comment by CraftManiakpl** [comment]
PS: Sorry for  my English, is so weak.

**Comment by whichtwix** [comment]
there already is a discord
