### ISSUE TITLE
[Suggestion] Imposter Role or Default Ability: Disperser

### ISSUE THREAD

**Issue by compton-scatter** [eDonnes124/Town-Of-Us-R#96]
Many lobbies, especially proxy chat ones, suffer from heavy grouping. This makes it significantly more difficult for imposters and to kill and if they do kill, they are often easily caught. To remedy this issue, the disperser role is proposed.

The disperser role or default ability will allow the imposter to, on a specified cooldown, have a selected or random subset of players be dispersed to random locations in the map.

**Comment by eDonnes124** [comment]
I actually like this as a 1 time use modifier. I'll have a think about it.
